### ISSUE TITLE
daff package removed from CRAN 

### ISSUE THREAD

**Issue by aylapear** [poissonconsulting/poispkgs#14]
The daff package has been removed from CRAN which is creating issues in installing poispkgs as it tries to grab it from CRAN.

https://cran.r-project.org/web/packages/daff/index.html

**Comment by joethorley** [comment]
yeah should update DESCRIPTION so that it references GitHub repo in remotes

**Comment by aylapear** [comment]
It was just temporary and is back being a CRAN package so a mute point now
